### ISSUE TITLE
libglapi.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by leviwheatcroft** [little-forest/docker-dropbox#1]
Just started seeing this error, having recently updated some packages on the host. Not sure what has actually caused this.

```
ImportError: libglapi.so.0: cannot open shared object file: No such file or directory
!! dropbox: fatal python exception:
['Traceback (most recent call last):\n', '  File "dropbox/client/main.pyc", line 262, in <module>\n', '  File "dropbox/foundation/navigation_service/factory.pyc", line 19, in <module>\n', '  File "dropbox/foundation/navigation_service/navigation_service_impl.pyc", line 57, in <module>\n', '  File "dropbox/foundation/html_views/electron/manager_factory.pyc", line 13, in <module>\n', '  File "dropbox/foundation/html_views/local/common/manager.pyc", line 33, in <module>\n', '  File "dropbox/client/features/model_registry.pyc", line 13, in <module>\n', '  File "dropbox/client/features/generated_models.pyc", line 279, in <module>\n', '  File "dropbox/client/features/previews/view_anchor.pyc", line 104, in <module>\n', '  File "<_bootstrap_overrides>", line 153, in load_module\n', 'ImportError: libglapi.so.0: cannot open shared object file: No such file or directory\n'] (error 3)
```

[This recent thread on dropboxforum](https://www.dropboxforum.com/t5/Dropbox-installs-integrations/Headless-install-on-Debian-libglapi-so-0-cannot-open-shared/td-p/396457) issue lists some additional libs required when installing on Ubuntu 18.04

```
sudo apt-get install libc6
sudo apt-get install libglapi-mesa
sudo apt-get install libxdamage1
sudo apt-get install libxfixes3
sudo apt-get install libxcb-glx0
sudo apt-get install libxcb-dri2-0
sudo apt-get install libxcb-dri3-0
sudo apt-get install libxcb-present0
sudo apt-get install libxcb-sync1
sudo apt-get install libxshmfence1
sudo apt-get install libxxf86vm1
```

not sure which of these we will need for alpine.

**Comment by little-forest** [comment]
I'm sorry for not responding for a very long time.

I was facing the same problem and tried to solve it with AlpineLinux but gave up.

I rebuilt a Docker image based on Ubuntu 18.04. The image size is larger, but it now runs the latest Dropbox client.

**Comment by little-forest** [comment]
@leviwheatcroft

I'm sorry for not responding for a very long time. And thank you for reporting the problem and suggesting improvements.

I was facing the same problem and tried to solve it with AlpineLinux but gave up.

I rebuilt a Docker image based on Ubuntu 18.04. The image size is larger, but it now runs the latest Dropbox client.
